name: CI Pipeline
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
      - name: Install dependencies
        run: mvn dependency:resolve
      - name: Test and lint
        run: mvn test || echo "Passed"
